Melkehitys 1023
NatLibFi/melinda-record-import-transformer-dummy pull request #1
Opened 2019-09-16 09:45 UTC by natlibfi-jonollil

### Package update:
Melinda-record-import-commons: '^6.0.0'

### Local test settings:
- quay.io/natlibfi/melinda-record-import-api:test
- quay.io/natlibfi/melinda-record-import-controller:test
- melinda-record-import-importer-dummy #melkehitys-1023 build locally
- melinda-record-import-transformer-dummy #melkehitys-1023 build locally

2019-09-18 12:23 UTC, ghost requested changes
Replace Helmet-specific texts (README has this too).

2019-09-18 12:23 UTC, natlibfi-arlehiko commented on src/cli.js
> +		name: 'melinda-record-import-transformer-helmet',
Fix name

2019-09-19 06:22 UTC, ghost requested changes
Remove this from README: 
```
 Consumes records as represented by Helmet's [Sierra ILS](https://sandbox.iii.com/iii/sierra-api/swagger/index.html)
```

2019-09-27 11:48 UTC, natlibfi-jonollil commented
If stream is given to dummy transformer, all records will be validated as valid and sent to importter.

2019-10-02 11:44 UTC, ghost requested changes
This needs the same changes as Helmet transformer (These should be implemented after Helmet transformer works correctly).

2019-10-11 11:02 UTC, ghost requested changes
Should be fixed when implementation is ready in API, commons and Helmet-transformer.

2019-10-14 14:34 UTC, ghost requested changes
[@natlibfi/melinda-record-import-commons](https://www.npmjs.com/package/@natlibfi/melinda-record-import-commons/v/7.0.0) has been published. Update dependency to point to that version in NPM.

2019-10-25 06:50 UTC, ghost approved these changes

2019-10-25 06:52 UTC, ghost requested changes
Files `test.json` and `test20.json` were probably included accidentally in version control, so please remove them.

2019-10-25 06:52 UTC, natlibfi-arlehiko commented on .drone.yml
>    image: node:8
Change to `node:10`.

2019-10-28 07:00 UTC, ghost approved these changes

2019-10-28 07:01 UTC, merged